platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'TicTacToe' do
  pod 'RIBs', :git => 'https://github.com/uber/RIBs.git', :tag => '0.9.2'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa', '~> 5.1'
end
